mitov2/config/routes.rb
Rails.application.routes.draw do
  resources :team_member_connections
  resources :teams, path: '/B_20_Pesho_Milev_connections'
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mitov2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mitov2/app/models/member.rb
class Member < ApplicationRecord
	has_many :team_member_connections
	has_many :teams, through: :team_member_connections
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

mitov2/app/models/team.rb
class Team < ApplicationRecord
	has_many :team_member_connections
	has_many :members, through: :team_member_connections
end

mitov2/app/models/team_member_connection.rb
class TeamMemberConnection < ApplicationRecord
	belongs_to :team
	belongs_to :member
	validate do
		if Member.find(self.member.id).teams.select{|t| t.color == Team.find(self.team_id).color}.count >= 1
			errors.add(:team_member_connections, "Already in a team wit that color")
		end
	end
end

mitov2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

mitov2/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

mitov2/app/controllers/team_member_connections_controller.rb
class TeamMemberConnectionsController < ApplicationController
  before_action :set_team_member_connection, only: [:show, :edit, :update, :destroy]

  # GET /team_member_connections
  # GET /team_member_connections.json
  def index
    @team_member_connections = TeamMemberConnection.all
  end

  # GET /team_member_connections/1
  # GET /team_member_connections/1.json
  def show
  end

  # GET /team_member_connections/new
  def new
    @team_member_connection = TeamMemberConnection.new
  end

  # GET /team_member_connections/1/edit
  def edit
  end

  # POST /team_member_connections
  # POST /team_member_connections.json
  def create
    @team_member_connection = TeamMemberConnection.new(team_member_connection_params)

    respond_to do |format|
      if @team_member_connection.save
        format.html { redirect_to @team_member_connection, notice: 'Team member connection was successfully created.' }
        format.json { render :show, status: :created, location: @team_member_connection }
      else
        format.html { render :new }
        format.json { render json: @team_member_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_member_connections/1
  # PATCH/PUT /team_member_connections/1.json
  def update
    respond_to do |format|
      if @team_member_connection.update(team_member_connection_params)
        format.html { redirect_to @team_member_connection, notice: 'Team member connection was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member_connection }
      else
        format.html { render :edit }
        format.json { render json: @team_member_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_member_connections/1
  # DELETE /team_member_connections/1.json
  def destroy
    @team_member_connection.destroy
    respond_to do |format|
      format.html { redirect_to team_member_connections_url, notice: 'Team member connection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member_connection
      @team_member_connection = TeamMemberConnection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_connection_params
      params.require(:team_member_connection).permit(:member_id, :team_id)
    end
end

mitov2/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :color)
    end
end

mitov2/app/helpers/application_helper.rb
module ApplicationHelper
end

mitov2/app/helpers/members_helper.rb
module MembersHelper
end

mitov2/app/helpers/team_member_connections_helper.rb
module TeamMemberConnectionsHelper
end

mitov2/app/helpers/teams_helper.rb
module TeamsHelper
end

mitov2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mitov2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mitov2/app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :member_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mitov2/app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

mitov2/app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

mitov2/app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

mitov2/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

mitov2/app/views/team_member_connections/_form.html.erb
<%= form_with(model: team_member_connection, local: true) do |form| %>
  <% if team_member_connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_member_connection.errors.count, "error") %> prohibited this team_member_connection from being saved:</h2>

      <ul>
      <% team_member_connection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.number_field :member_id, id: :team_member_connection_member_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id, id: :team_member_connection_team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mitov2/app/views/team_member_connections/edit.html.erb
<h1>Editing Team Member Connection</h1>

<%= render 'form', team_member_connection: @team_member_connection %>

<%= link_to 'Show', @team_member_connection %> |
<%= link_to 'Back', team_member_connections_path %>

mitov2/app/views/team_member_connections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Member Connections</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_member_connections.each do |team_member_connection| %>
      <tr>
        <td><%= team_member_connection.member_id %></td>
        <td><%= team_member_connection.team_id %></td>
        <td><%= link_to 'Show', team_member_connection %></td>
        <td><%= link_to 'Edit', edit_team_member_connection_path(team_member_connection) %></td>
        <td><%= link_to 'Destroy', team_member_connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Member Connection', new_team_member_connection_path %>

mitov2/app/views/team_member_connections/new.html.erb
<h1>New Team Member Connection</h1>

<%= render 'form', team_member_connection: @team_member_connection %>

<%= link_to 'Back', team_member_connections_path %>

mitov2/app/views/team_member_connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @team_member_connection.member_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @team_member_connection.team_id %>
</p>

<%= link_to 'Edit', edit_team_member_connection_path(@team_member_connection) %> |
<%= link_to 'Back', team_member_connections_path %>