mitov/config/routes.rb
Rails.application.routes.draw do
  resources :manufactors
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mitov/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mitov/app/models/car.rb
class Car < ApplicationRecord
	belongs_to :manufactor
	validate do
		if self.model != "red" && self.model != "green" && self.model != "blue"
			errors.add(:model, "Only red greeen and blue cars allowed!")			
		end
	end
	validate do
		if Manufactor.find(self.manufactor_id).cars.select{ |c| c.date.year == self.date.year && c.model == self.model}.count == 3
			errors.add(:cars, "Too many cars with that color for this year!")
		end
	end
end

mitov/app/models/manufactor.rb
class Manufactor < ApplicationRecord
	has_many :cars
end

mitov/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

mitov/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:number, :model, :date, :manufactor_id)
    end
end

mitov/app/controllers/manufactors_controller.rb
class ManufactorsController < ApplicationController
  before_action :set_manufactor, only: [:show, :edit, :update, :destroy]

  # GET /manufactors
  # GET /manufactors.json
  def index
    @manufactors = Manufactor.all
  end

  # GET /manufactors/1
  # GET /manufactors/1.json
  def show
  end

  # GET /manufactors/new
  def new
    @manufactor = Manufactor.new
  end

  # GET /manufactors/1/edit
  def edit
  end

  # POST /manufactors
  # POST /manufactors.json
  def create
    @manufactor = Manufactor.new(manufactor_params)

    respond_to do |format|
      if @manufactor.save
        format.html { redirect_to @manufactor, notice: 'Manufactor was successfully created.' }
        format.json { render :show, status: :created, location: @manufactor }
      else
        format.html { render :new }
        format.json { render json: @manufactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufactors/1
  # PATCH/PUT /manufactors/1.json
  def update
    respond_to do |format|
      if @manufactor.update(manufactor_params)
        format.html { redirect_to @manufactor, notice: 'Manufactor was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufactor }
      else
        format.html { render :edit }
        format.json { render json: @manufactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufactors/1
  # DELETE /manufactors/1.json
  def destroy
    @manufactor.destroy
    respond_to do |format|
      format.html { redirect_to manufactors_url, notice: 'Manufactor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufactor
      @manufactor = Manufactor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufactor_params
      params.require(:manufactor).permit(:name, :location)
    end
end

mitov/app/helpers/application_helper.rb
module ApplicationHelper
end

mitov/app/helpers/cars_helper.rb
module CarsHelper
end

mitov/app/helpers/manufactors_helper.rb
module ManufactorsHelper
end

mitov/app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :car_number %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :car_date %>
  </div>

  <div class="field">
    <%= form.label :manufactor_id %>
    <%= form.number_field :manufactor_id, id: :car_manufactor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mitov/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

mitov/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Model</th>
      <th>Date</th>
      <th>Manufactor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.number %></td>
        <td><%= car.model %></td>
        <td><%= car.date %></td>
        <td><%= car.manufactor_id %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

mitov/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

mitov/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @car.number %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Date:</strong>
  <%= @car.date %>
</p>

<p>
  <strong>Manufactor:</strong>
  <%= @car.manufactor_id %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

mitov/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mitov</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mitov/app/views/manufactors/_form.html.erb
<%= form_with(model: manufactor, local: true) do |form| %>
  <% if manufactor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manufactor.errors.count, "error") %> prohibited this manufactor from being saved:</h2>

      <ul>
      <% manufactor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :manufactor_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :manufactor_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mitov/app/views/manufactors/edit.html.erb
<h1>Editing Manufactor</h1>

<%= render 'form', manufactor: @manufactor %>

<%= link_to 'Show', @manufactor %> |
<%= link_to 'Back', manufactors_path %>

mitov/app/views/manufactors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manufactors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manufactors.each do |manufactor| %>
      <tr>
        <td><%= manufactor.name %></td>
        <td><%= manufactor.location %></td>
        <td><%= link_to 'Show', manufactor %></td>
        <td><%= link_to 'Edit', edit_manufactor_path(manufactor) %></td>
        <td><%= link_to 'Destroy', manufactor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufactor', new_manufactor_path %>

mitov/app/views/manufactors/new.html.erb
<h1>New Manufactor</h1>

<%= render 'form', manufactor: @manufactor %>

<%= link_to 'Back', manufactors_path %>

mitov/app/views/manufactors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manufactor.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @manufactor.location %>
</p>

<%= link_to 'Edit', edit_manufactor_path(@manufactor) %> |
<%= link_to 'Back', manufactors_path %>